#!/bin/sh

OPENCOR_DIR="$(cd "$(dirname "$0")"; pwd)"

PYTHONPATH=$PYTHONPATH:/opt/conda/lib/python3.5/site-packages:/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg:/opt/conda/lib/python3.5/site-packages/IPython/extensions

${OPENCOR_DIR}/bin/OpenCOR $*
